# Generated by Django 3.2.9 on 2021-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extradata_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='proj',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
